

DROP TABLE IF EXISTS "Playlists" CASCADE;
CREATE TABLE "Playlists"
(
	"id" CHAR(22) NOT NULL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"is_deleted" BOOL NOT NULL DEFAULT FALSE
);


DROP TABLE IF EXISTS "Songs" CASCADE;
CREATE TABLE "Songs"
(
	"id" CHAR(22) NOT NULL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"album" TEXT NOT NULL,
	"artists" TEXT NOT NULL,
	"artwork" TEXT DEFAULT NULL,
	"start" INT NOT NULL DEFAULT 0,
	"duration" INT NOT NULL DEFAULT 0,
	"is_deleted" BOOL NOT NULL DEFAULT FALSE,
	"Playlists.id" CHAR(22) NOT NULL,
	FOREIGN KEY ("Playlists.id") REFERENCES "Playlists" ("id")
);
